title       = "gbfs"
baseURL     = "https://gbfs-cli.tamnd.com/"
description = "A command line for gbfs."
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/gbfs-cli"
